replicaCount: 1

image:
  imageName: nvcr.io/nvidia/tritonserver:26.01-py3
  pullPolicy: IfNotPresent
  modelRepositoryPath: /models
  numGpus: 1

gpuModels:
  - "TYPE_GPU_USED"

service:
  type: ClusterIP

modelRepository:
  existingClaim: model-repository-pvc
  subdirectory: ""